### ISSUE TITLE
Missing LICENSE info

### ISSUE THREAD

**Issue by yaxu** [falkTX/Hylia#1]
I'm really thankful for this library!
Could you clarify the license for it please? 
I'd suggest GPLv3 but of course up to you.
Ableton link is 'GPLv2 or later', it seems the info is missing from your hard fork of that too?

**Comment by falkTX** [comment]
We can just follow GPLv2+ from link.
Assume that to be the case here.
The code like https://github.com/falkTX/Hylia/blob/master/hylia.h already mentions this.

**Comment by yaxu** [comment]
Ok thanks
